name: image

on:
  push:
    branches:
      - image

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: ~1.22.2

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Build
        run: ci/build.sh

      - name: build
        run: go build

      - name: image
        run: ./images chrome -b 137.0.7151.68-1 -d 137.0.7151.68 -t selenoid/vnc:chrome_137.0
      - name: image
        run: docker save -o selenoid-vnc-chrome-137.tar  selenoid/vnc:chrome_137.0

      - name: upload
        uses: actions/upload-artifact@v4
        with:
#          name: docker-images-tar
          path: selenoid-vnc-chrome-136.tar
          retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

